//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenThanhDuyLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee(string v1, string v2, string v3, string v4, int v5, int v6)
        {
        }

        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Department { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<int> EmployeeType { get; set; }
    
        public virtual EmpType EmpType { get; set; }
    }
}
